# Use this file to deploy ETLer to a Kubernetes cluster.
#
# This deployment requires configuration. You can load, for example, using the
# command below:
#     `kubectl create configmap etl-pipeline-config --from-env-file=.env`
#
# Deploy with the following command:
# kubectl apply -f deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-pipeline
  labels:
    app: etl-pipeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etl-pipeline
  template:
    metadata:
      labels:
        app: etl-pipeline
    spec:
      containers:
      - name: etl-pipeline
        image: etl-pipeline:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: etl-pipeline-config
      restartPolicy: Always